### ISSUE TITLE
Will extraction of points (SpatialPoints) be supported at some point?

### ISSUE THREAD

**Issue by Martin-Jung** [hunzikp/velox#1]
Hey there,

Very nice package. 
Currently only SpatialPolygons are supported by the extract function. Are there any plans to allow the input of SpatialPoints as well? 
I am working with RasterStacks and want to process individual coordinates.

Cheers,
Martin

**Comment by hunzikp** [comment]
Hi Martin. Thanks for the kind words. Should be easy to implement point extraction. Will look into this in the coming week.
-ph

**Comment by hunzikp** [comment]
Well, it took longer than I hoped, but point extraction is now supported. Use method `vx$extract_points(sp)`, see `?VeloxRaster_extract_points`
