### ISSUE TITLE
Error during line extract / rasterize

### ISSUE THREAD

**Issue by chschoenenberger** [hunzikp/velox#18]
Hi Philipp

The package sounds really promising after working with a rather large dataset and the raster package being terribly slow. Unfortunately, I was not able to use it though. I have a large SpatialLinesDataFrame (~84'000 Elements) and I'd like to extract values from a digital elevation model of Switzerland (7972 x 18545 cells). I tried to do it with a subset first, but I always got the same error:
```
Error in boostFactory$makeBoxGrid(origin = origin, dim = dim, res = res) : 
  std::bad_alloc
```
The same happenes when I try to rasterize the line (for a subsequent raster overlay).  Did you encounter this before or do you know how to resolve it? If you wish some test data you can contact me by email: christoph.schoenenberger@uzh.ch.

Thanks for the great work. 

Best regards,
Chris

**Comment by hunzikp** [comment]
We discussed this bilaterally and it turns out that the issue was insufficient RAM. This is not technically a bug, so I'm going to close this issue. However, I'll keep memory management on my to do list.
