### ISSUE TITLE
Error in if (is_float32) { : missing value where TRUE/FALSE needed

### ISSUE THREAD

**Issue by Canderson156** [hunzikp/velox#24]
Hello,

I'm trying to write my velox Raster to a .tif file and recieve the following message:

> vLC2$write("test.tif", overwrite = TRUE)
Error in if (is_float32) { : missing value where TRUE/FALSE needed

**Comment by hunzikp** [comment]
Hi Christine,
Thx for the message. Could you post a reproducible example and indicate what version of velox/R you are using?

**Comment by lilyhahn** [comment]
I'm having the same issue. Trying to load the attached image, extracting a single band, and writing it fails with `Error in if (is_float32) { : missing value where TRUE/FALSE needed`.  
    f = velox("LC08_026028_20130520.tif")  
    rband = velox(f$rasterbands[1], extent = f$extent, res = f$res)  
    rband$write(path = "band1.tif")  
[LC08_026028_20130520.zip](https://github.com/hunzikp/velox/files/1876806/LC08_026028_20130520.zip)

**Comment by nbarsch** [comment]
bump

Having the same issue.

**Comment by ozjimbob** [comment]
Yep same problem here.

**Comment by hunzikp** [comment]
I think this is fixed in the development version (0.2.0.9002); at least I don't get any error when replicating @rainshapes' example. Can one of you guys `devtools::install_github('hunzikp/velox')` and confirm?

**Comment by pascaloettli** [comment]
@hunzikp  I confirm it works with the development version

**Comment by hunzikp** [comment]
Thanks @pascaloettli!
